# Generated by Django 4.0.1 on 2022-01-20 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POST',
            fields=[
                ('Post_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Post_Title', models.CharField(max_length=200)),
                ('Post_Description', models.CharField(max_length=200)),
                ('Post_image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('User_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Birthday', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='POST_COMMENT',
            fields=[
                ('Comment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Comment', models.CharField(max_length=200)),
                ('Post_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialmedia.post')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialmedia.user')),
            ],
        ),
        migrations.CreateModel(
            name='LIKED_POST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialmedia.post')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialmedia.user')),
            ],
        ),
    ]
