# Generated by Django 4.0.1 on 2022-01-20 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEST',
            fields=[
                ('Comment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Comment', models.CharField(max_length=200)),
                ('Post_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialmedia.post')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialmedia.user')),
            ],
        ),
    ]
