# Generated by Django 4.0.1 on 2022-01-20 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TEST',
        ),
    ]
