# Generated by Django 4.0.1 on 2022-01-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0005_user_age_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='LIKED_POST2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.CharField(max_length=200)),
                ('Post_ID', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='POST_COMMENT2',
            fields=[
                ('Comment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('User_ID', models.CharField(max_length=200)),
                ('Post_ID', models.CharField(max_length=200)),
                ('Comment', models.CharField(max_length=200)),
            ],
        ),
    ]
